<template>
  <div>
    <div class="p-6 rounded-lg shadow-lg" v-if="$t('en')=='en'">
  <h1 class="text-3xl font-semibold mb-4 text-center">Privacy Policy</h1>
  <p class="text-sm">Impulse Limited (“Impulse”) is a global company with its headquarters in Grand Cayman that develops, implements, and supports proprietary customer care and solutions for service providers within telecommunications sectors in 40+ countries.</p>
  <p class="text-sm">Impulse is fully committed to ensuring the proper management and use of all personal data it collects and handles it in compliance with applicable privacy laws, including the Australian Privacy Act 1988 (Cth), the EU General Data Protection Regulation (GDPR), the UK Data Protection Act (DPA), and the principles of the EU-U.S. Data Privacy Framework including the UK Extension to the EU-U.S. Data Privacy Framework.</p>
  <p>This privacy policy (“Privacy Policy”) applies to Impulse Limited, as set out in the Appendix. It sets out Impulse’s policy on the management of personal data. </p>
  <h2 class="text-2xl font-semibold mt-4">1. OPEN AND TRANSPARENT MANAGEMENT OF PERSONAL DATA</h2>
  <p class="text-sm">Impulse is committed to ensuring that it is open and transparent about the way it manages personal data. Set out in this Privacy Policy is the following important information regarding our management of your personal data:</p>
  <ul class="list-decimal ml-8">
    <li>The kinds of personal data that Impulse collects and holds</li>
    <li>How Impulse collects personal data and the purposes for which Impulse collects, holds and uses personal data; </li>
    <li>Who Impulse discloses personal data to;</li>
    <li>How an individual may access its personal data that is held by Impulse and seek the correction of such information;</li>
    <li>How an individual may complain about a privacy issue or alleged breach of privacy and how Impulse will deal with such a complaint.</li>
  </ul>
  <h2 class="text-2xl font-semibold mt-8">2. PERSONAL DATA IMPULSE COLLECTS AND USES</h2>
  <p class="text-sm">Impulse will only collect personal data that is necessary for its business functions and activities. It will only collect personal data by lawful and fair means and not in an obtrusive way. Impulse collects and holds different categories of personal data depending on the purposes for which it is collected and processed. We ensure that our staff are trained in regard to their obligations in handling personal data.</p>
  <p class="text-sm">The following types of personal data may be collected and processed:</p>
  <ul class="list-decimal ml-8">
    <li>Information about partners, customers (including potential partners and customers) and their employees and customers</li> 
  </ul>
  <p class="text-sm mt-2">When your company becomes a partner, customer, or prospective customer or partner of Impulse, then, in the course of establishing the business relationship, we may collect personal data about certain customer employees such as name, work location, employer, position, and business contact details. We may collect this information when you or your organization give it to us directly, when we receive it from our partners or suppliers who are allowed to share your information with us, when you use our products and services, or visit our website.</p>
  <p class="text-sm mt-2">All personal data collected by Impulse is solely used for our legitimate business functions and activities. It may be used to the extent that it is necessary for us to carry out our business of the supply of our products / solutions and services and to provide you with information in relation to our products/ solutions, services, or other information that you may have requested. For example: </p>
  <p class="text-sm mt-2">We may collect and store information about the training you take for our products in order to provide you with appropriate credentials and to be able to verify authorised users.</p>
  <p class="text-sm mt-2">We may take down the details and notes of business meetings and may share this information within Impulse globally on a need-to-know basis. </p>
  <p class="text-sm mt-2">When you as a customer contact impulse for support services, your phone call may be recorded for administrative and quality assurance purposes. </p>
  <p class="text-sm mt-2">We may use the information we collect to analyse, improve and develop our products and services including contacting you for customer satisfaction surveys. </p>
  <p class="text-sm mt-2">Where you participate in a webinar, you understand and agree that other participants may see the information you provide in the shared webinar platform and that the webinar may be recorded for future purposes, including making available for future training. </p>
  <p class="text-sm mt-2">Sometimes, as part of a service being provided to a customer, Impulse may also collect and retain, on behalf of that customer, personal data relating to that customer’s customers. In that scenario, Impulse is a data processor, and Impulse and the customer will have a Data Processing Agreement in place. The personal data of the end customer will be collected directly from Impulse’s customer and may include, name, billing address, contact and account information and meter data. An example of this would be when Impulse provides hosting or managed solutions on behalf of a customer or where we provide support or maintenance services for our customers, and it is not reasonably practical to use anonymised materials. This personal data is solely held in accordance with our customer’s requirements and instructions so that we can facilitate provision of the services our customers have requested. If you are a current or former customer of one of Impulse’s customers and you wish to access, correct, amend, or delete your personal data, please direct your request to the applicable Impulse customer first (ie, to the company which collected your personal data from you), and then, if no satisfactory response is received, please contact: privacy@impulse.ky. Impulse will work with our customer to endeavour to resolve your request. </p>
  <p class="text-sm mt-2">We will retain such personal data that we process on behalf of our customers only for as long as is needed to provide our services. </p>
  <ul class="list-decimal ml-8">
    <li>Recruitment</li>     
  </ul>
  <p class="text-sm mt-2">In connection with a job application or inquiry, you may provide us with information about yourself, such as your name, address, contact information, resume, cover letter and your references. We may request you to send a video application, complete a task relevant to the job applied for and take notes during interviews with you. We may also require your social security number, passport copy or other relevant right-to-work documentation in order to verify your working rights in the country you’ve applied for employment. In addition, where consented by you, we may process information about your disability in order to accommodate you. </p>
    <p class="text-sm mt-2">In some cases, we may receive your personal data from our recruitment suppliers, to whom you have given the permission to share your information with us, or you may send your application to us through an external job application software or integration provider. We may also share your personal data with and receive it from third parties where we, for example, do background checks, including police checks (as permitted by local laws), verify your visa status, references, or qualifications, or arrange pre-employment assessments, such as personality tests with external providers. </p>
    <p class="text-sm mt-2">We may use your information throughout Impulse globally in order to address your inquiry or consider you for employment purposes, to market our events, send you surveys related to our recruitment process, and perform analysis on our job applicant base. By submitting your application, you consent to the processing of your personal data as set out in this privacy policy. Unless you tell us not to do so, we may keep your information for future consideration in accordance with our retention policy. </p>
    <p class="text-sm mt-2">If you are offered and accept employment with Impulse, the personal data collected during the recruitment process may be included in your employment record and be retained in accordance with Impulse’s retention policy. Employees should liaise with their HR contact to obtain a copy of the separate employee data privacy policy. </p>
  <ul class="list-decimal ml-8 mt-2">
    <li>Information about Impulse’s contractors and suppliers and their employees </li>     
  </ul>
  <p class="text-sm mt-2">Impulse may collect personal data of our contractors and suppliers. This personal data may include name and business contact details so that we can contact them. </p>
  <p class="text-sm italic mt-2">If personal data is not provided </p>  
  <p class="text-sm mt-2">If you do not provide us with your personal data when requested, this may limit the assistance we are able to provide to you. For example, we may not be able to provide the product or service you may have requested, to handle enquiries in connection with those products or services, or to proceed with your application. </p>  
  <p class="text-sm italic mt-2">Personal data of third parties </p>
  <p class="text-sm mt-2">If you provide us personal data about any person other than yourself, you must ensure that they understand how their personal data will be used, and that they have given their permission for you to disclose it to us and for you to allow us, and our suppliers (as applicable), to use it as set out in this Privacy Policy. </p>
  <p class="text-sm italic mt-2">Legal basis </p>
  <p class="text-sm mt-2">Impulse may process personal data for Impulse Group’s legitimate business purposes, such as the performance of a contract (including pre-contractual measures), to comply with Impulse’s legal obligations and as required for Impulse’s legitimate interests e.g., to conduct and organise business, protect its legal interests and secure its IT environment. In some cases, the processing of personal data is based on your consent. </p>
  <p class="text-sm italic mt-2">Sensitive personal data </p>
  <p class="text-sm mt-2">We will only collect sensitive data about you where we have obtained your consent to do so, or we are required or authorised by law to do so. </p>
  <h2 class="text-2xl font-semibold mt-4">3. QUALITY OF PERSONAL DATA </h2>
  <p class="text-sm mt-2">Impulse will ensure, to the extent reasonably possible, that personal data collected, used, or disclosed is accurate, up-to-date, complete, and relevant. If Impulse becomes aware that any of the personal data it holds is inaccurate, it will take prompt steps to update its records so that those records are correct. Please be aware that in circumstances where Impulse is processing personal data on behalf of a customer of Impulse (as described above) we are unable to correct incorrect personal data, but we will work with our customer in regard to correcting any inaccuracy. </p>
  <h2 class="text-2xl font-semibold mt-4">4. DATA SECURITY </h2>
  <p class="text-sm mt-2">Impulse takes reasonable steps to implement appropriate technical and organisational measures to protect the personal data it holds from misuse, interference, loss and unauthorised access, modification, or disclosure. </p>
  <p class="text-sm mt-2">All personal data is stored at secure premises and is accessed only by authorised personnel for permitted purposes. Electronic personal data is stored using quality data management tools and IT security systems and controls including encryption, passwords, and firewalls. Our security systems are regularly reviewed and audited so that we can identify any potential security weaknesses and take steps to promptly rectify them. </p>  
  <p class="text-sm mt-4">
    The Impulse US Entities (as defined in the Appendix) comply with the EU-U.S. Data Privacy Framework (EU-U.S. DPF) and the UK Extension to the EU-U.S. DPF, as set forth by the U.S. Department of Commerce. The Impulse US Entities have certified to the U.S. Department of Commerce that they adhere to the EU-U.S. Data Privacy Framework Principles (EU-U.S. DPF Principles) with regard to the processing of personal data received from the European Union and the United Kingdom in reliance on the EU-U.S. DPF and the UK Extension to the EU-U.S. DPF. If there is any conflict between the terms in this privacy policy and the EU-U.S. DPF Principles the Principles shall govern. To learn more about the Data Privacy Framework (DPF) program, and to view our certification, please visit <a href="https://www.dataprivacyframework.gov/" class="text-blue-500 hover:underline">https://www.dataprivacyframework.gov/</a>.
  </p>
  <p class="text-sm mt-4">
  In compliance with the EU-U.S. DPF and the UK Extension to the EU-U.S. DPF, the Impulse US Entities commit to resolve DPF Principles-related complaints about our collection and use of your personal information. EU and UK individuals with inquiries or complaints regarding our handling of personal data received in reliance on the EU-U.S. DPF and the UK Extension to the EU-U.S. DPF, should first contact Impulse at: <a href="mailto:privacy@impulse.ky" class="text-blue-500 hover:underline">privacy@impulse.ky</a>.
</p>
<p class="text-sm mt-4">
  In compliance with the EU-U.S. DPF and the UK Extension to the EU-U.S. DPF, the Impulse US Entities commit to refer unresolved complaints concerning our handling of personal data received in reliance on the EU-U.S. DPF and the UK Extension to the EU-U.S. DPF to International Centre for Dispute Resolution/American Arbitration Association (“AAA-ICDR”), an alternative dispute resolution provider based in the United States. If you do not receive timely acknowledgment of your DPF Principles-related complaint from us, or if we have not addressed your DPF Principles-related complaint to your satisfaction, please visit <a href="https://go.adr.org/dpf_irm.html" class="text-blue-500 hover:underline">https://go.adr.org/dpf_irm.html</a> for more information or to file a complaint. The services of AAA-ICDR are provided at no cost to you.
</p>
<p class="text-sm mt-4">
  The Impulse US Entities remain liable for violations by onward transfer recipients acting as agents that process such information in a manner inconsistent with the EU-U.S. DPF or the UK Extension to the EU-U.S. DPF, unless the relevant Impulse US Entity proves that it is not responsible for the event giving rise to the damage.
</p>
<h2 class="text-2xl font-semibold mt-4">5. DIRECT MARKETING </h2>
<p class="text-sm mt-2">Impulse will only engage in direct marketing practices in accordance with the law. At any time, you can request to no longer receive any marketing material or information from Impulse via email or the unsubscribe link in our marketing emails. </p>
<p class="text-sm mt-2">We may use paid channels, such as LinkedIn or Google to deliver Impulse mass-targeted advertisements based on e.g., industry segments or job titles on their platforms. </p>
<h2 class="text-2xl font-semibold mt-4">6. DISCLOSURE AND RETENTION OF PERSONAL DATA, AND TRANSFERS TO THIRD COUNTRIES </h2>
<p class="text-sm mt-4">
  In order to perform activities in connection with the purposes described in this Privacy Policy, we may make your personal data available to other persons or entities, or disclose it to them, including our suppliers and service providers and any other third parties notified to you in connection with the collection of your personal data.
</p>
<p class="text-sm mt-4">
  Some of the information you provide to us may be transferred cross border for Impulse’s legitimate business purposes and only on a need-to-know basis. Impulse will primarily rely on adequacy decisions but there may also be transfers to a “third country” that may not be covered by an adequacy decision by the European Commission or the competent authority of your country. In most instances, the transfers will be to an affiliated company within the Impulse Group (these are listed in the Appendix) given the global nature of Impulse’s business but may also include third parties as described herein.
</p>
<p class="text-sm mt-4">
  Wherever transfers of personal data to third countries occurs (even if it is to another company within the Impulse Group), Impulse puts in place appropriate safeguards to protect your personal data and transfers your personal data in compliance with the applicable data privacy laws. Impulse has entered into the EU standard contractual clauses (and the UK equivalent) (the “SCCs”) where required. A copy of the relevant SCCs is available to the data subject upon request.
</p>

<p class="text-sm mt-4">
  Where personal data is transferred within Impulse, Impulse applies the same security measures globally. We use our best endeavours to ensure that the third parties we engage with implement technical and organisational measures consistent with our own measures. In addition, we undertake data security due diligence on our partners and ensure that these partners conform to appropriate accreditations.
</p>
<p class="text-sm mt-4">
  We will not sell, rent, or lease personal information to third parties other than business partners or agents. We will not disclose such information to business partners without first letting you know and offering you an opportunity to opt-out or otherwise prohibit disclosure to that business partner. We will also provide you the opportunity to let us know if you wish to opt out of all disclosures to business partners.
</p>

<p class="text-sm mt-4">
  We will only transfer personal information to our agent in order that such agent processes personal data pursuant to our instructions and only after assuring that the agent has privacy policies in effect for such personal data which are at least as stringent as those contained in this Privacy Policy.
</p>
<p class="text-sm mt-4">
  We may also share your data with professional advisers such as our lawyers and insurers to manage risks and legal claims.
</p>
<p class="text-sm mt-4">
  Impulse will cooperate with all third parties to enforce their intellectual property or other rights. We will also cooperate with lawful requests by public authorities, including to meet national security or law enforcement requirements from within or outside your country of residence, for example, Impulse is subject to the investigatory and enforcement powers of the Federal Trade Commission (FTC). This may include disclosing your personal information to government or law enforcement agencies, or private parties, when we have a good faith belief that disclosure is required by law or when we, in our discretion, believe that disclosure is necessary to protect our legal rights, or those of third parties and/or to comply with a judicial proceeding, court order, fraud reduction or legal process served on us. In such cases, we may raise or waive any legal objection or right available to us. These uses of your personal data are in our legitimate interests of protecting our business security.
</p>
<p class="text-sm mt-4">
  Personal data will only be retained for as long as it is necessary to fulfill the purposes for which it is collected and processed, to comply with Impulse’s legal obligations (such as financial regulation) and for Impulse’s legitimate interests, such as defending itself against legal claims. Personal data is retained in accordance with Impulse’s data retention policy and, when no longer needed, reasonable steps are taken to securely delete the personal data.
</p>
<h2 class="text-2xl font-semibold mt-4">7. WEBSITE BROWSING </h2>
<p class="text-sm mt-4">Impulse’s website uses ‘cookies’ to keep track of your user session on our site for statistical purposes and will result in some information being logged including the time of access, your IP address and the pages that have been viewed or accessed. If you reject cookies, you can still use our website, but your ability to use some features may be limited. </p>
<p class="text-sm mt-4">Impulse’s website may include relevant hyperlinks to external websites not controlled by Impulse. Whilst all reasonable care has been exercised in selecting and providing any such links, Impulse does not verify the safety or security of the content which may be provided to you. </p>
<h2 class="text-2xl font-semibold mt-4">8. YOUR RIGHTS  </h2>
<p class="text-sm mt-4">Your exact rights are subject to the data privacy laws that are applicable to you. The following rights relate specifically to EU and UK data subjects. Subject to verification of your identity, if we hold personal data about you then you may make a request to access, update or correct this personal data at any time. </p>
<p class="text-sm mt-4">You may also request that we remove any personal data that we may hold. This enables you to ask us to delete or remove personal data for example where you consider that we do not need it any longer for the purposes for which we originally collected it as explained to you in this Privacy Policy, where you have withdrawn your consent to our using it and we had relied on that consent according to this Privacy Policy, where you consider that we cannot show a ‘legitimate interest’ in continuing to process it and we have relied on that legitimate interest to process it as explained to you in this Privacy Policy. </p>
<p class="text-sm mt-4">You may have the right to object to us continuing to use or disclose your personal data, where we are relying on a legitimate interest, (or those of a third party) and there is something about your particular situation which makes you want to object to processing on this ground as you feel it impacts on your fundamental rights. In some cases, we may demonstrate that we have compelling legitimate grounds to process your information which override your rights. You also have the right to object where we are processing your personal data for direct marketing purposes. In certain circumstances, you may also have the right to obtain restriction of processing. </p>
<p class="text-sm mt-4">If you have provided your consent to the collection, processing, and transfer of your personal data, you have the right to fully or partly withdraw your consent. Once we have received notification that you have withdrawn your consent, we will no longer process your information for the purpose(s) to which you originally consented unless there is another legal ground for the processing. </p>
<p class="text-sm mt-4">All requests related to your personal data and any complaint relating to the handling and management of personal data by Impulse or any breach of the applicable privacy laws, should be addressed to: </p>
<p class="text-sm mt-4">
  The Privacy Officer <br>
  Impulse Limited <br>
  38 Caterpillar Lane, Grand Cayman <br>
  Cayman Islands <br>
  Email: <a href="mailto:privacyofficer@Impulsecx.com">privacyofficer@Impulsecx.com</a>
</p>
<p class="text-sm mt-4">We will respond to your request regarding your personal data in accordance with applicable data privacy laws, which for EU and UK data subjects is 1 month. </p>
<p class="text-sm mt-4">This Privacy Policy can be obtained via www.impulse.ky/privacy or by contacting Impulse’s Privacy Officer at the address above. </p>
<p class="text-sm mt-4">Where required by the applicable data privacy laws in your country, the controller of your personal data is the main Impulse Group company that is located in your country, unless Impulse Corporation Pty Ltd or another Impulse affiliate has identified itself as the controller. </p>
<p class="text-sm mt-4">
  Impulse’s Privacy Officer will commence an investigation into any complaint made by you to Impulse. You will be informed of the outcome of your complaint following completion of the investigation. In the event that you are dissatisfied with the outcome of your complaint, you may refer the complaint to the data privacy authorities in your country, which for Australia is the Office of the Australian Information Privacy Commission at <a href="https://www.oaic.gov.au/">https://www.oaic.gov.au/</a> or if the complaint is GDPR-related, the supervisory authority of your country: <a href="https://edpb.europa.eu/about-edpb/about-edpb/members_en">https://edpb.europa.eu/about-edpb/about-edpb/members_en</a>, or if UK DPA related, the Information Commissioner’s Office at <a href="https://ico.org.uk/">https://ico.org.uk/</a>.
</p>
<p class="text-sm mt-4">Impulse reserves the right to amend this Privacy Policy at any time. This Privacy Statement was last updated in July 2023. </p>
<h2 class="text-2xl font-semibold mt-4">APPENDIX </h2>
</div>
<div class="p-6 rounded-lg shadow-lg" v-else>
  <h1 class="text-3xl font-semibold mb-4 text-center">Política de privacidad</h1>
  <p class="text-sm">Impulse Limited (“Impulse”) es una empresa global con sede en Grand Cayman que desarrolla, implementa y respalda soluciones y servicios de atención al cliente propietarios para proveedores de servicios en más de 40 países.</p>
  <p class="text-sm">Impulse está plenamente comprometida a garantizar la correcta gestión y uso de todos los datos personales que recopila y los maneja de conformidad con las leyes de privacidad aplicables, incluida la Ley de Privacidad Australiana de 1988 (Cth), el Reglamento General de Protección de Datos (GDPR) de la UE, la Ley de Protección de Datos del Reino Unido (DPA) y los principios del Marco de Privacidad de Datos UE-EE. UU., incluida la Extensión del Reino Unido al Marco de Privacidad de Datos UE-EE. UU.</p>
  <p>Esta política de privacidad (“Política de privacidad”) se aplica a Impulse Limited, según lo establecido en el Apéndice. Establece la política de Impulse sobre la gestión de datos personales. </p>
  <h2 class="text-2xl font-semibold mt-4">1. GESTIÓN ABIERTA Y TRANSPARENTE DE DATOS PERSONALES</h2>
  <p class="text-sm">Impulse se compromete a garantizar que sea abierto y transparente sobre la forma en que maneja los datos personales. En esta Política de privacidad se encuentra la siguiente información importante sobre nuestra gestión de sus datos personales:</p>
  <ul class="list-decimal ml-8">
    <li>Los tipos de datos personales que Impulse recopila y conserva</li>
    <li>Cómo Impulse recopila datos personales y los fines para los que recopila, conserva y utiliza datos personales; </li>
    <li>A quién Impulse divulga datos personales;</li>
    <li>Cómo un individuo puede acceder a sus datos personales que son retenidos por Impulse y solicitar la corrección de dicha información;</li>
    <li>Cómo un individuo puede presentar una queja sobre un problema de privacidad o una presunta violación de la privacidad y cómo Impulse tratará dicha queja.</li>
  </ul>
  <h2 class="text-2xl font-semibold mt-8">2. DATOS PERSONALES QUE IMPULSE RECOPILA Y UTILIZA</h2>
  <p class="text-sm">Impulse solo recopilará datos personales que sean necesarios para sus funciones y actividades comerciales. Solo recopilará datos personales de manera legal y justa y no de manera intrusiva. Impulse recopila y conserva diferentes categorías de datos personales según los fines para los que se recopilan y procesan. Nos aseguramos de que nuestro personal esté capacitado en cuanto a sus obligaciones en el manejo de datos personales.</p>
  <p class="text-sm">Los siguientes tipos de datos personales pueden ser recopilados y procesados:</p>
  <ul class="list-decimal ml-8">
    <li>Información sobre socios, clientes (incluidos socios y clientes potenciales) y sus empleados y clientes</li> 
  </ul>
  <p class="text-sm mt-2">Cuando su empresa se convierte en socio, cliente o cliente potencial de Impulse, entonces, en el curso de establecer la relación comercial, podemos recopilar datos personales sobre ciertos empleados de clientes, como nombre, ubicación de trabajo, empleador, cargo y detalles de contacto comercial. Podemos recopilar esta información cuando usted o su organización nos la proporcionen directamente, cuando la recibimos de nuestros socios o proveedores que tienen permitido compartir su información con nosotros, cuando utiliza nuestros productos y servicios o visita nuestro sitio web.</p>
  <p class="text-sm mt-2">Todos los datos personales recopilados por Impulse se utilizan únicamente para nuestras funciones y actividades comerciales legítimas. Se puede usar en la medida en que sea necesario para que llevemos a cabo nuestro negocio de suministro de nuestros productos/soluciones y servicios y para proporcionarle información en relación con nuestros productos/soluciones, servicios u otra información que pueda haber solicitado. Por ejemplo: </p>
  <p class="text-sm mt-2">Podemos recopilar y almacenar información sobre la capacitación que recibe para nuestros productos con el fin de proporcionarle credenciales apropiadas y poder verificar usuarios autorizados.</p>
  <p class="text-sm mt-2">Podemos registrar los detalles y notas de las reuniones comerciales y podemos compartir esta información dentro de Impulse a nivel mundial según sea necesario.</p>
  <p class="text-sm mt-2">Cuando usted, como cliente, se contacta con Impulse para servicios de soporte, su llamada telefónica puede ser grabada con fines administrativos y de garantía de calidad.</p>
  <p class="text-sm mt-2">Podemos utilizar la información que recopilamos para analizar, mejorar y desarrollar nuestros productos y servicios, incluido contactarlo para encuestas de satisfacción del cliente.</p>
  <p class="text-sm mt-2">Cuando participe en un seminario web, comprende y acepta que otros participantes pueden ver la información que proporciona en la plataforma de seminarios web compartida y que el seminario web puede ser grabado para futuros fines, incluida la disponibilidad para futuras capacitaciones.</p>
  <p class="text-sm mt-2">A veces, como parte de un servicio prestado a un cliente, Impulse también puede recopilar y retener, en nombre de ese cliente, datos personales relacionados con los clientes de ese cliente. En ese escenario, Impulse es un procesador de datos, y Impulse y el cliente tendrán un Acuerdo de Procesamiento de Datos en su lugar. Los datos personales del cliente final se recopilarán directamente del cliente de Impulse e pueden incluir, nombre, dirección de facturación, información de contacto y cuenta y datos de medición. Un ejemplo de esto sería cuando Impulse proporciona alojamiento o soluciones administradas en nombre de un cliente o cuando proporcionamos soporte o servicios de mantenimiento para nuestros clientes, y no es razonablemente práctico utilizar materiales anonimizados. Estos datos personales se retienen únicamente de acuerdo con los requisitos e instrucciones de nuestro cliente para que podamos facilitar la provisión de los servicios que nuestros clientes hayan solicitado. Si es un cliente
de Impulse actual o anterior y desea acceder, corregir, enmendar o eliminar sus datos personales, dirija su solicitud al cliente de Impulse correspondiente primero (es decir, a la empresa que recopiló sus datos personales de usted) y luego, si no recibe una respuesta satisfactoria, comuníquese con: privacy@impulse.ky. Impulse trabajará con nuestro cliente para intentar resolver su solicitud.</p>
  <p class="text-sm mt-2">Retendremos dichos datos personales que procesamos en nombre de nuestros clientes solo durante el tiempo que sea necesario para proporcionar nuestros servicios.</p>
  <ul class="list-decimal ml-8">
    <li>Reclutamiento</li>     
  </ul>
  <p class="text-sm mt-2">En relación con una solicitud de empleo o consulta, es posible que nos proporcione información sobre usted, como su nombre, dirección, información de contacto, currículum vitae, carta de presentación y sus referencias. Es posible que le solicitemos que envíe una solicitud de video, complete una tarea relevante para el trabajo solicitado y tome notas durante las entrevistas con usted. También podemos requerir su número de seguro social, copia del pasaporte u otra documentación relevante de derecho a trabajar para verificar sus derechos laborales en el país para el que ha solicitado empleo. Además, cuando usted lo consienta, podemos procesar información sobre su discapacidad para acomodarlo.</p>
<p class="text-sm mt-2">En algunos casos, podemos recibir sus datos personales de nuestros proveedores de contratación, a quienes les ha dado permiso para compartir su información con nosotros, o puede enviarnos su solicitud a través de un software externo de solicitud de empleo o proveedor de integración. También podemos compartir su información personal con y recibirla de terceros donde, por ejemplo, realizamos verificaciones de antecedentes, incluidas verificaciones policiales (según lo permitan las leyes locales), verificamos su estado de visa, referencias o calificaciones, o realizamos evaluaciones previas al empleo, como pruebas de personalidad con proveedores externos.</p>
<p class="text-sm mt-2">Podemos usar su información en toda Impulse globalmente para abordar su consulta o considerarlo para fines de empleo, para comercializar nuestros eventos, enviarle encuestas relacionadas con nuestro proceso de reclutamiento y realizar análisis sobre nuestra base de solicitantes de empleo. Al enviar su solicitud, usted acepta el procesamiento de sus datos personales según se establece en esta política de privacidad. A menos que nos indique lo contrario, podemos conservar su información para consideraciones futuras de acuerdo con nuestra política de retención.</p>
<p class="text-sm mt-2">Si se le ofrece y acepta un empleo en Impulse, los datos personales recopilados durante el proceso de reclutamiento pueden incluirse en su expediente laboral y se conservarán de acuerdo con la política de retención de Impulse. Los empleados deben comunicarse con su contacto de recursos humanos para obtener una copia de la política de privacidad de datos de empleados por separado.</p>
<ul class="list-decimal ml-8 mt-2">
  <li>Información sobre contratistas y proveedores de Impulse y sus empleados</li>     
</ul>
<p class="text-sm mt-2">Impulse puede recopilar datos personales de nuestros contratistas y proveedores. Estos datos personales pueden incluir nombre y detalles de contacto comercial para que podamos comunicarnos con ellos.</p>
<p class="text-sm italic mt-2">Si no se proporcionan datos personales</p>  
<p class="text-sm mt-2">Si no nos proporciona sus datos personales cuando se le solicite, esto puede limitar la asistencia que podemos brindarle. Por ejemplo, es posible que no podamos proporcionar el producto o servicio que haya solicitado, manejar consultas relacionadas con esos productos o servicios, o proceder con su solicitud.</p>  
<p class="text-sm italic mt-2">Datos personales de terceros</p>
<p class="text-sm mt-2">Si nos proporciona datos personales sobre cualquier persona que no sea usted mismo, debe asegurarse de que comprendan cómo se utilizarán sus datos personales y de que hayan dado su permiso para que nos los divulgue a nosotros y para que nos permita, y a nuestros proveedores (según corresponda), utilizarlos según se establece en esta Política de privacidad.</p>
<p class="text-sm italic mt-2">Base legal</p>
<p class="text-sm mt-2">Impulse puede procesar datos personales para fines comerciales legítimos del Grupo Impulse, como el cumplimiento de un contrato (incluidas medidas precontractuales), para cumplir con las obligaciones legales de Impulse y según sea necesario para los intereses legítimos de Impulse, por ejemplo, para llevar a cabo y organizar negocios, proteger sus intereses legales y asegurar su entorno informático. En algunos casos, el procesamiento de datos personales se basa en su consentimiento.</p>
<p class="text-sm italic mt-2">Datos personales sensibles</p>
<p class="text-sm mt-2">Solo recopilaremos datos sensibles sobre usted si hemos obtenido su consentimiento para hacerlo o si estamos obligados o autorizados por la ley para hacerlo.</p>
<h2 class="text-2xl font-semibold mt-4">3. CALIDAD DE LOS DATOS PERSONALES </h2>
<p class="text-sm mt-2">Impulse garantizará, en la medida de lo razonablemente posible, que los datos personales recopilados, utilizados o divulgados sean precisos, estén actualizados, completos y relevantes. Si Impulse se da cuenta de que alguno de los datos personales que posee es inexacto, tomará medidas rápidas para actualizar sus registros para que esos registros sean correctos. Tenga en cuenta que en circunstancias en las que Impulse esté procesando datos personales en nombre de un cliente de Impulse (como se describe anteriormente), no podemos corregir datos personales incorrectos, pero trabajaremos con nuestro cliente para corregir cualquier inexactitud.</p>
<h2 class="text-2xl font-semibold mt-4">4. SEGURIDAD DE DATOS </h2>
<p class="text-sm mt-2">Impulse toma medidas razonables para implementar medidas técnicas y organizativas adecuadas para proteger los datos personales que posee contra el uso indebido, la interferencia, la pérdida y el acceso no autorizado, la modificación o divulgación. </p>
<p class="text-sm mt-2">Todos los datos personales se almacenan en instalaciones seguras y solo son accesibles por personal autorizado para fines permitidos. Los datos personales electrónicos se almacenan utilizando herramientas de gestión de datos de calidad y sistemas y controles de seguridad informática que incluyen cifrado, contraseñas y firewalls. Nuestros sistemas de seguridad se revisan y auditan regularmente para identificar posibles debilidades de seguridad y tomar medidas para corregirlas rápidamente. </p>
<p class="text-sm mt-4">
  Las Entidades de Impulse en los EE. UU. (según se define en el Apéndice) cumplen con el Marco de privacidad de datos UE-EE. UU. (EU-U.S. DPF) y la Extensión del Reino Unido al EU-U.S. DPF, según lo
establecido por el Departamento de Comercio de los Estados Unidos. Las Entidades de Impulse en los EE. UU. han certificado al Departamento de Comercio de los EE. UU. que cumplen con los Principios del Marco de Privacidad de Datos UE-EE. UU. (Principios EU-U.S. DPF) con respecto al procesamiento de datos personales recibidos de la Unión Europea y el Reino Unido confiando en el EU-U.S. DPF y la Extensión del Reino Unido al EU-U.S. DPF. Si hay algún conflicto entre los términos en esta política de privacidad y los Principios EU-U.S. DPF, los Principios regirán. Para obtener más información sobre el programa de Marco de Privacidad de Datos (DPF) y ver nuestra certificación, visite <a href="https://www.dataprivacyframework.gov/" class="text-blue-500 hover:underline">https://www.dataprivacyframework.gov/</a>.
</p>
<p class="text-sm mt-4">
  En cumplimiento con el EU-U.S. DPF y la Extensión del Reino Unido al EU-U.S. DPF, las Entidades de Impulse en los Estados Unidos se comprometen a resolver quejas relacionadas con los Principios del DPF sobre nuestra recopilación y uso de su información personal. Las personas de la UE y el Reino Unido con consultas o quejas con respecto a nuestro manejo de datos personales recibidos confiando en el EU-U.S. DPF y la Extensión del Reino Unido al EU-U.S. DPF, deben comunicarse primero con Impulse a: <a href="mailto:privacy@impulse.ky" class="text-blue-500 hover:underline">privacy@impulse.ky</a>.
</p>
<p class="text-sm mt-4">
  En cumplimiento con el EU-U.S. DPF y la Extensión del Reino Unido al EU-U.S. DPF, las Entidades de Impulse en los Estados Unidos se comprometen a remitir quejas no resueltas relacionadas con nuestro manejo de datos personales recibidos confiando en el EU-U.S. DPF y la Extensión del Reino Unido al EU-U.S. DPF al Centro Internacional de Resolución de Disputas/Asociación Americana de Arbitraje ("AAA-ICDR"), un proveedor de resolución de disputas alternativo con sede en los Estados Unidos. Si no recibe un reconocimiento oportuno de su queja relacionada con los Principios del DPF de nuestra parte, o si no hemos abordado su queja relacionada con los Principios del DPF de manera satisfactoria, visite <a href="https://go.adr.org/dpf_irm.html" class="text-blue-500 hover:underline">https://go.adr.org/dpf_irm.html</a> para obtener más información o para presentar una queja. Los servicios de AAA-ICDR se proporcionan sin costo alguno para usted.
</p>
<p class="text-sm mt-4">
  Las Entidades de Impulse en los Estados Unidos siguen siendo responsables de las violaciones de los destinatarios de transferencias posteriores que actúan como agentes y procesan dicha información de manera inconsistente con el EU-U.S. DPF o la Extensión del Reino Unido al EU-U.S. DPF, a menos que la Entidad de Impulse relevante demuestre que no es responsable del evento que dio lugar al daño.
</p>
<h2 class="text-2xl font-semibold mt-4">5. MARKETING DIRECTO </h2>
<p class="text-sm mt-2">Impulse solo participará en prácticas de marketing directo de acuerdo con la ley. En cualquier momento, puede solicitar no recibir más material o información de marketing de Impulse por correo electrónico o haciendo clic en el enlace para cancelar suscripción en nuestros correos electrónicos de marketing. </p>
<p class="text-sm mt-2">Podemos utilizar canales pagados, como LinkedIn o Google, para entregar anuncios masivos de Impulse basados, por ejemplo, en segmentos de la industria o títulos de trabajo en sus plataformas. </p>
<h2 class="text-2xl font-semibold mt-4">6. DIVULGACIÓN Y RETENCIÓN DE DATOS PERSONALES, Y TRANSFERENCIAS A TERCEROS PAÍSES </h2>
<p class="text-sm mt-4">
  Para llevar a cabo actividades relacionadas con los propósitos descritos en esta Política de Privacidad, podemos poner su información personal a disposición de otras personas o entidades, o divulgarla a ellas, incluidos nuestros proveedores y prestadores de servicios y cualquier otro tercero notificado a usted en relación con la recopilación de su información personal.
</p>
<p class="text-sm mt-4">
  Algunas de las información que nos proporciona pueden transferirse transfronteras para los fines comerciales legítimos de Impulse y solo sobre la base de la necesidad de saber. Impulse confiará principalmente en decisiones de adecuación, pero también puede haber transferencias a un "tercer país" que puede no estar cubierto por una decisión de adecuación de la Comisión Europea o la autoridad competente de su país. En la mayoría de los casos, las transferencias serán a una empresa afiliada dentro del Grupo Impulse (que se enumeran en el Apéndice) dada la naturaleza global del negocio de Impulse, pero también pueden incluir terceros según se describe aquí.
</p>
<p class="text-sm mt-4">
  Donde sea que ocurran transferencias de datos personales a terceros países (incluso si es a otra empresa dentro del Grupo Impulse), Impulse implementa garantías adecuadas para proteger sus datos personales y transfiera sus datos personales cumpliendo con las leyes de privacidad de datos aplicables. Impulse ha celebrado las cláusulas contractuales tipo de la UE (y su equivalente en el Reino Unido) (las "CCT") cuando sea necesario. Se proporcionará una copia de las CCT relevantes al interesado previa solicitud.
</p>

<p class="text-sm mt-4">
  Cuando se transfieran datos personales dentro de Impulse, Impulse aplica las mismas medidas de seguridad a nivel global. Hacemos todo lo posible para garantizar que los terceros con los que nos relacionamos implementen medidas técnicas y organizativas consistentes con nuestras propias medidas. Además, realizamos una debida diligencia en seguridad de datos en nuestros socios y nos aseguramos de que estos socios se adhieran a las acreditaciones apropiadas.
</p>
<p class="text-sm mt-4">
  No venderemos, alquilaremos ni arrendaremos información personal a terceros que no sean socios comerciales o agentes. No divulgaremos dicha información a socios comerciales sin informarle primero y ofrecerle la oportunidad de optar por no participar o prohibir de otro modo la divulgación a ese socio comercial. También le proporcionaremos la oportunidad de informarnos si desea optar por no participar en todas las divulgaciones a socios comerciales.
</p>

<p class="text-sm mt-4">
  Solo transferiremos información personal a nuestro agente para que dicho agente procese datos personales de acuerdo con nuestras instrucciones y solo después de asegurarnos de que el agente tenga políticas de privacidad en vigencia para dichos datos personales que sean al menos tan estrictas como las contenidas en esta Política de Privacidad.
</p>
<p class="text-sm mt-4">
  También podemos compartir sus datos con asesores profesionales como nuestros abogados y aseguradores para gestionar riesgos y reclamaciones legales.
</p>
<p class="text-sm mt-4">
  Impulse cooperará con todos los terceros para hacer valer sus derechos de propiedad intelectual u otros derechos. También cooperaremos con las solicitudes legales de autoridades públicas, incluido el cumplimiento de requisitos de seguridad nacional o cumplimiento de la ley desde dentro o fuera de su país de residencia, por ejemplo, Impulse está sujeta a los poderes de investigación y ejecución de la Comisión Federal de Comercio (FTC). Esto puede incluir la divulgación de su información personal a agencias gubernamentales o de aplicación de la ley, o partes privadas, cuando tengamos una creencia de buena fe de que la divulgación es requerida por ley o cuando, a nuestra discreción, creemos que la divulgación es necesaria para proteger nuestros derechos legales o los de terceros y/o para cumplir con un proceso judicial, orden judicial, reducción de fraude o proceso legal que se nos sirva. En tales casos, podemos plantear o renunciar a cualquier objeción legal o derecho disponible para nosotros. Estos usos de sus datos personales están en nuestros intereses legítimos de proteger la seguridad de nuestro negocio.
</p>
<p class="text-sm mt-4">
  Los datos personales solo se conservarán durante el tiempo que sea necesario para cumplir con los fines para los que se recopilan y procesan, para cumplir con las obligaciones legales de Impulse (como la regulación financiera) y para los intereses legítimos de Impulse, como defenderse contra reclamos legales. Los datos personales se conservan de acuerdo con la política de retención de datos de Impulse y, cuando ya no sean necesarios, se toman medidas razonables para eliminar de manera segura los datos personales.
</p>
<h2 class="text-2xl font-semibold mt-4">7. NAVEGACIÓN EN EL SITIO WEB </h2>
<p class="text-sm mt-4">El sitio web de Impulse utiliza 'cookies' para realizar un seguimiento de su sesión de usuario en nuestro sitio con fines estadísticos y resultará en el registro de alguna información, incluida la hora de acceso, su dirección IP y las páginas que se han visto o accedido. Si rechaza las cookies, aún puede usar nuestro sitio web, pero es posible que su capacidad para utilizar algunas funciones esté limitada. </p>
<p class="text-sm mt-4">El sitio web de Impulse puede incluir hipervínculos relevantes a sitios web externos no controlados por Impulse. Aunque se ha ejercido todo el cuidado razonable en la selección y provisión de dichos enlaces, Impulse no verifica la seguridad o la seguridad del contenido que se le puede proporcionar. </p>
<h2 class="text-2xl font-semibold mt-4">8. SUS DERECHOS  </h2>
<p class="text-sm mt-4">Sus derechos exactos están sujetos a las leyes de privacidad de datos que le sean aplicables. Los siguientes derechos se relacionan específicamente con los sujetos de datos de la UE y el Reino Unido. Sujeto a la verificación de su identidad, si tenemos datos personales sobre usted, puede hacer una solicitud para acceder, actualizar o corregir estos datos personales en cualquier momento. </p>
<p class="text-sm mt-4">También puede solicitar que eliminemos cualquier dato personal que podamos tener. Esto le permite pedirnos que eliminemos o eliminemos datos personales, por ejemplo, cuando considere que no lo necesitamos más para los fines para los que los recopilamos originalmente como se explica en esta Política de privacidad, cuando haya retirado su consentimiento para nuestro uso y confiamos en ese consentimiento de acuerdo con esta Política de privacidad, cuando considere que no podemos mostrar un 'interés legítimo' en seguir procesándolo y hemos confiado en ese interés legítimo para procesarlo como se explica en esta Política de privacidad. </p>
<p class="text-sm mt-4">Puede tener el derecho de oponerse a que continuemos usando o divulgando sus datos personales, donde confiamos en un interés legítimo, (o en los de un tercero) y haya algo sobre su situación particular que haga que desee oponerse al procesamiento en este terreno como usted siente que impacta en sus derechos fundamentales. En algunos casos, podemos demostrar que tenemos motivos legítimos imperiosos para procesar su información que prevalecen sobre sus derechos. También tiene derecho a oponerse cuando estemos procesando sus datos personales con fines de marketing directo. En ciertas circunstancias, también puede tener derecho a obtener una restricción del procesamiento. </p>
<p class="text-sm mt-4">Si ha proporcionado su consentimiento para la recopilación, procesamiento y transferencia de sus datos personales, tiene derecho a retirar total o parcialmente su consentimiento. Una vez que hayamos recibido la notificación de que ha retirado su consentimiento, ya no procesaremos su información para el (los) propósito (s) para el (los) que originalmente dio su consentimiento a menos que haya otro fundamento legal para el procesamiento. </p>
<p class="text-sm mt-4">Todas las solicitudes relacionadas con sus datos personales y cualquier queja relacionada con el manejo y gestión de datos personales por parte de Impulse o cualquier violación de las leyes de privacidad aplicables, deben dirigirse a: </p>
<p class="text-sm mt-4">
  El Oficial de Privacidad <br>
  Impulse Limited <br>
  38 Caterpillar Lane, Grand Cayman <br>
  Islas Caimán <br>
  Email: <a href="mailto:privacyofficer@Impulsecx.com">privacyofficer@Impulsecx.com</a>
</p>
<p class="text-sm mt-4">Responderemos a su solicitud con respecto a sus datos personales de acuerdo con las leyes aplicables de privacidad de datos, que para los sujetos de datos de la UE y el Reino Unido es de 1 mes. </p>
<p class="text-sm mt-4">Esta Política de Privacidad se puede obtener a través de www.impulse.ky/privacy o poniéndose en contacto con el Oficial de Privacidad de Impulse en la dirección indicada arriba. </p>
<p class="text-sm mt-4">Cuando lo requieran las leyes aplicables de privacidad de datos en su país, el controlador de sus datos personales es la empresa principal del Grupo Impulse que se encuentra en su país, a menos que Impulse Corporation Pty Ltd u otra filial de Impulse se haya identificado como el controlador. </p>
<p class="text-sm mt-4">
  El Oficial de Privacidad de Impulse iniciará una investigación sobre cualquier queja presentada por usted a Impulse. Se le informará del resultado de su queja una vez completada la investigación. En caso de que no esté satisfecho con el resultado de su queja, puede remitir la queja a las autoridades de privacidad de datos en su país, que para Australia es la Oficina del Comisionado Australiano de Información de Privacidad en <a href="https://www.oaic.gov.au/">https://www.oaic.gov.au/</a>, o si la queja está relacionada con el GDPR, la autoridad supervisora de su país: <a href="https://edpb.europa.eu/about-edpb/about-edpb/members_en">https://edpb.europa.eu/about-edpb/about-edpb/members_en</a>, o si está relacionada con la DPA del Reino Unido, la Oficina del Comisionado de Información en <a href="https://ico.org.uk/">https://ico.org.uk/</a>.
</p>
<p class="text-sm mt-4">Impulse se reserva el derecho de modificar esta Política de Privacidad en cualquier momento. Esta Declaración de Privacidad fue actualizada por última vez en julio de 2023. </p>
<h2 class="text-2xl font-semibold mt-4">APÉNDICE </h2>
</div>

</div>

</template>
